language: objective-c
osx_image: xcode10.3
xcode_workspace: SJVideoPlayer/Example/SJVideoPlayer.xcworkspace
podfile: SJVideoPlayer/Example/Podfile

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

notifications:
  email: false

before_install: 
    - gem install cocoapods 
    - pod --version
    - pod update --project-directory=Example/
