language: objective-c
osx_image: xcode11.2

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

notifications:
  email: true

before_install: 
    - gem install cocoapods 
    - pod --version

script:
  - pwd
  - ls
  - pod trunk push --allow-warnings --verbose --use-libraries